services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
volumes:
  - ./backend:/app
  - /app/node_modules  # <-- Diese Zeile hinzufügen
  - gameolympics-data:/app/data
    # Wir geben dem Container die .env-Datei mit den Geheimnissen
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

# Hier definieren wir den sicheren Speicherort für die Datenbank
volumes:
  gameolympics-data:
